/* V269 — compléments vérifiés de la bibliothèque de duʿā’.
   Texte du corpus coranique canonique embarqué : QuranEnc,
   traduction Muhammad Hamidullah, version 1.0.2 du 2025-07-02. */
window.JDC_DUA_LIBRARY_ADDITIONS = [
  {id:'q2-201',title:'Le bien ici-bas et dans l’au-delà',category:'Espérance',tags:['bien','au-delà','protection'],arabic:'رَبَّنَآ ءَاتِنَا فِي ٱلدُّنۡيَا حَسَنَةٗ وَفِي ٱلۡأٓخِرَةِ حَسَنَةٗ وَقِنَا عَذَابَ ٱلنَّارِ',translit:'',fr:'Seigneur ! Accorde nous belle part ici-bas, et belle part aussi dans l’au-delà; et protège-nous du châtiment du Feu !',source:'Coran 2:201 · QuranEnc / Muhammad Hamidullah',grade:'📖 Coran'},
  {id:'q2-286',title:'Pardon, miséricorde et soulagement',category:'Pardon',tags:['pardon','miséricorde','épreuve'],arabic:'رَبَّنَا لَا تُؤَاخِذۡنَآ إِن نَّسِينَآ أَوۡ أَخۡطَأۡنَاۚ رَبَّنَا وَلَا تَحۡمِلۡ عَلَيۡنَآ إِصۡرٗا كَمَا حَمَلۡتَهُۥ عَلَى ٱلَّذِينَ مِن قَبۡلِنَاۚ رَبَّنَا وَلَا تُحَمِّلۡنَا مَا لَا طَاقَةَ لَنَا بِهِۦۖ وَٱعۡفُ عَنَّا وَٱغۡفِرۡ لَنَا وَٱرۡحَمۡنَآۚ أَنتَ مَوۡلَىٰنَا فَٱنصُرۡنَا عَلَى ٱلۡقَوۡمِ ٱلۡكَٰفِرِينَ',translit:'',fr:'Seigneur ! Ne nous châtie pas s’il nous arrive d’oublier ou de commettre une erreur. Seigneur ! Ne nous charge pas d’un fardeau lourd comme Tu as chargé ceux qui vécurent avant nous. Seigneur ! Ne nous impose pas ce que nous ne pouvons supporter, efface nos fautes, pardonne-nous et fais nous miséricorde. Tu es Notre Maître, accorde-nous donc la victoire sur les peuples infidèles.',source:'Coran 2:286 · QuranEnc / Muhammad Hamidullah',grade:'📖 Coran'},
  {id:'q3-8',title:'Pour garder un cœur guidé',category:'Guidance',tags:['cœur','guidance','miséricorde'],arabic:'رَبَّنَا لَا تُزِغۡ قُلُوبَنَا بَعۡدَ إِذۡ هَدَيۡتَنَا وَهَبۡ لَنَا مِن لَّدُنكَ رَحۡمَةًۚ إِنَّكَ أَنتَ ٱلۡوَهَّابُ',translit:'',fr:'Seigneur ! Ne laisse pas dévier nos cœurs après que Tu nous aies guidés; et accorde-nous Ta miséricorde. C’est Toi, certes, le Grand Donateur !',source:'Coran 3:8 · QuranEnc / Muhammad Hamidullah',grade:'📖 Coran'},
  {id:'q3-147',title:'Pardon et fermeté',category:'Pardon',tags:['pardon','fermeté','épreuve'],arabic:'رَبَّنَا ٱغۡفِرۡ لَنَا ذُنُوبَنَا وَإِسۡرَافَنَا فِيٓ أَمۡرِنَا وَثَبِّتۡ أَقۡدَامَنَا وَٱنصُرۡنَا عَلَى ٱلۡقَوۡمِ ٱلۡكَٰفِرِينَ',translit:'',fr:'Seigneur ! Pardonne-nous nos péchés ainsi que nos excès dans nos comportements, affermis nos pas et donne-nous la victoire sur les gens mécréants !',source:'Coran 3:147 · QuranEnc / Muhammad Hamidullah',grade:'📖 Coran'},
  {id:'q18-10',title:'Miséricorde et droiture dans mes affaires',category:'Guidance',tags:['miséricorde','droiture','affaires'],arabic:'رَبَّنَآ ءَاتِنَا مِن لَّدُنكَ رَحۡمَةٗ وَهَيِّئۡ لَنَا مِنۡ أَمۡرِنَا رَشَدٗا',translit:'',fr:'Ô notre Seigneur ! Donne-nous de Ta part une miséricorde ! Et assure nous la droiture dans tout ce qui nous concerne.',source:'Coran 18:10 · QuranEnc / Muhammad Hamidullah',grade:'📖 Coran'},
  {id:'q20-114',title:'Accroître mon savoir',category:'Savoir',tags:['savoir','études','connaissance'],arabic:'رَّبِّ زِدۡنِي عِلۡمٗا',translit:'',fr:'Mon Seigneur ! Accroît mon savoir !',source:'Coran 20:114 · QuranEnc / Muhammad Hamidullah',grade:'📖 Coran'},
  {id:'q66-8',title:'Parfaire notre lumière',category:'Espérance',tags:['lumière','pardon','repentir'],arabic:'رَبَّنَآ أَتۡمِمۡ لَنَا نُورَنَا وَٱغۡفِرۡ لَنَآۖ إِنَّكَ عَلَىٰ كُلِّ شَيۡءٖ قَدِيرٞ',translit:'',fr:'Seigneur, parfais-nous notre lumière et pardonne-nous. Car Tu es Omnipotent.',source:'Coran 66:8 · QuranEnc / Muhammad Hamidullah',grade:'📖 Coran'},
  {id:'q1-6',title:'Être guidé sur le droit chemin',category:'Guidance',tags:['guidance','droiture','prière'],arabic:'ٱهۡدِنَا ٱلصِّرَٰطَ ٱلۡمُسۡتَقِيمَ',translit:'',fr:'Guide-nous dans le droit chemin,',source:'Coran 1:6 · QuranEnc / Muhammad Hamidullah',grade:'📖 Coran',note:'Le verset suivant (1:7) complète le contexte de cette invocation.'}
];
window.JDC_mergeDuas=base=>{const identity=d=>String(d.arabic||'').normalize('NFKD').replace(/[\u064B-\u065F\u0670\sۖۗۚۛ۞]/g,''),ref=d=>String(d.source||'').split(' · ')[0],ids=new Set(base.map(d=>d.id)),texts=new Set(base.map(identity)),refs=new Set(base.map(ref));window.JDC_DUA_LIBRARY_ADDITIONS.forEach(d=>{const key=identity(d),r=ref(d);if(!ids.has(d.id)&&key&&!texts.has(key)&&r&&!refs.has(r)){base.push(d);ids.add(d.id);texts.add(key);refs.add(r)}})};
function openLibraryDua(id){const d=DUA_LIBRARY.find(x=>x.id===id);if(!d)return;openModal(d.title,`<div dir="rtl" class="jdc-inline-13">${escapeHtml(d.arabic)}</div>${d.translit?`<p class="jdc-inline-14"><em>${escapeHtml(d.translit)}</em></p>`:''}<p class="jdc-inline-14">${escapeHtml(d.fr)}</p>${d.note?`<p class="subtle"><strong>Quand / répétition :</strong> ${escapeHtml(d.note)}</p>`:''}<p class="subtle"><strong>${escapeHtml(d.grade)}</strong><br>${escapeHtml(d.source)}</p><div class="toolbar-row"><button class="mini-btn primary-mini" id="listenLibraryDua">🔊 Écouter</button><button class="mini-btn" id="copyLibraryDua">Copier</button><button class="mini-btn" id="favLibraryDua">${isLibraryFav(d.id)?'♥ Favori':'♡ Favori'}</button></div>`);document.getElementById('listenLibraryDua').onclick=()=>{if(!('speechSynthesis'in window))return toast('Lecture vocale indisponible');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(d.arabic);u.lang='ar';speechSynthesis.speak(u)};document.getElementById('copyLibraryDua').onclick=async()=>{try{await navigator.clipboard.writeText([d.arabic,d.translit,d.fr,d.source].filter(Boolean).join('\n'));toast('Du‘â copiée')}catch(e){toast('Copie indisponible')}};document.getElementById('favLibraryDua').onclick=()=>{toggleLibraryFav(d.id);closeModal()}}
