#!/usr/bin/env python3
import json, hashlib, re, sys
from pathlib import Path
R=Path(__file__).resolve().parents[1]; okc=0; fail=0
def check(name,cond,detail=''):
 global okc,fail; okc+=bool(cond);fail+=not bool(cond);print(('PASS' if cond else 'FAIL'),name,detail)
def load(p): return json.loads((R/p).read_text('utf-8'))
sup=load('data/religious-library-hadith-new-authenticated-canonical-supplement-v1.json'); cs=sup['canonicalStructures']; ids=[x['id'] for x in cs]
legacy=load('data/religious-library-hadith-canonical-consolidation-v44.json')['canonicalStructuralEntries']; legacy_refs={x['primaryRef'] for x in legacy}; supplement_refs={x['primaryRef'] for x in cs}
quran=load('data/religious-library-quran-canonical.json')['entries']; unified=load('data/religious-library-canonical-corpus-v1.json'); ue=unified['entries']; ukeys=[x['canonicalKey'] for x in ue]
check('unified-release',unified['release']=='V136');check('unified-counts',unified['counts']=={'quran':43,'hadithLegacy':69,'hadithSupplement':71,'hadithTotal':140,'religiousTotal':183,'unmaterializedPositions':0});check('unified-length',len(ue)==183);check('unified-keys-unique',len(ukeys)==len(set(ukeys)));check('unified-partitions',[sum(x['corpusPart']==part for x in ue) for part in ('quran','hadithLegacy','hadithSupplement')]==[43,69,71]);check('unified-order',[x['corpusPart'] for x in ue]==['quran']*43+['hadithLegacy']*69+['hadithSupplement']*71);check('unified-quran-exact',[x['payload'] for x in ue[:43]]==quran);check('unified-legacy-exact',[x['payload'] for x in ue[43:112]]==legacy);check('unified-supplement-exact',[x['payload'] for x in ue[112:]]==cs);check('unified-readiness-truthful',unified['policy']['structuralCoverageComplete'] is True and unified['policy']['editorialProductionReady'] is False and unified['policy']['publishedFrenchTranslationSynthesized'] is False)
editorial=load('data/religious-library-hadith-editorial-readiness-audit-v1.json'); ee=editorial['entries']; eids=[x['canonicalId'] for x in ee]
check('editorial-release',editorial['release']=='V137');check('editorial-counts',editorial['counts']=={'canonicalHadithStructures':140,'legacyStructures':69,'supplementStructures':71,'readyWithPublishedFrenchTextAndProvenance':0,'pendingCanonicalFrenchTextOrProvenance':140,'legacyWithoutCanonicalFrenchTextField':69,'supplementExplicitlyPendingPublishedFrenchProvenance':71});check('editorial-length',len(ee)==140);check('editorial-ids-unique',len(eids)==len(set(eids)));check('editorial-partitions',[sum(x['corpusPartition']==part for x in ee) for part in ('hadithLegacy','hadithSupplement')]==[69,71]);check('editorial-ready-zero',sum(x['productionReady'] is True for x in ee)==0);check('editorial-legacy-pending',all(x['publishedFrenchTranslation'] is None and x['canonicalFrenchTextPresent'] is False and x['canonicalFrenchProvenancePresent'] is False for x in ee[:69]));check('editorial-supplement-pending',all(x['publishedFrenchTranslation'] is None and x['editorialStatus']=='PENDING_PUBLISHED_FRENCH_PROVENANCE' for x in ee[69:]));check('editorial-id-alignment',eids==[x['canonicalId'] for x in legacy]+[x['id'] for x in cs]);check('editorial-policy-safe',editorial['policy']['editorialProductionReady'] is False and editorial['policy']['runtimeIntegrationAuthorized'] is False and editorial['policy']['automaticTranslationAcceptedAsPublishedSource'] is False)
fr1=load('data/religious-library-hadith-french-recovery-batch1-v1.json'); fe=fr1['entries']
check('french-batch1-release',fr1['release']=='V138');check('french-batch1-ids',[x['canonicalId'] for x in fe]==['RC-001','RC-002','RC-003','RC-004','RC-005']);check('french-batch1-counts',fr1['counts']=={'canonicalStructuresAudited':5,'historicalFrenchSummariesFound':5,'publishedFrenchTranslationsRecovered':0,'entriesStillPendingPublishedFrenchProvenance':5});check('french-batch1-not-promoted',all(x['historicalField']=='auditSummaryFr' and x['historicalPublishedFrenchTranslation'] is None and x['publishedFrenchTranslation'] is None and x['frenchProvenance'] is None and x['productionReady'] is False for x in fe));check('french-batch1-safe',fr1['assertions']=={'historicalSummariesPromotedAsTranslations':False,'translationSynthesized':False,'canonicalReligiousStructuresChanged':False,'runtimeChanged':False,'runtimeIntegrationAuthorized':False})
frx=load('data/religious-library-hadith-french-external-source-audit-batch1-v1.json'); fxe=frx['entries']
check('french-external-release',frx['release']=='V139');check('french-external-ids',[x['canonicalId'] for x in fxe]==['RC-001','RC-002','RC-003','RC-004','RC-005']);check('french-external-counts',frx['counts']=={'canonicalStructuresAudited':5,'exactFrenchReferencePagesLocated':3,'pagesWithExplicitRevisionWarning':2,'pagesWithoutRecoverableDisplayedVersionNumber':3,'translationsPromoted':0,'entriesStillPending':5});check('french-external-located',[x['sourceLocated'] for x in fxe]==[False,True,True,False,True]);check('french-external-none-promoted',all(x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in fxe));check('french-external-safe',frx['assertions']=={'webTextCopiedIntoCanonicalRegister':False,'translationSynthesized':False,'sourceWarningsIgnored':False,'reuseConditionsClaimedSatisfied':False,'canonicalReligiousStructuresChanged':False,'runtimeChanged':False,'runtimeIntegrationAuthorized':False})
frc=load('data/religious-library-hadith-published-french-canonical-v1.json'); frce=frc['entries']
check('french-canonical-release',frc['release']=='V199');check('french-canonical-counts',frc['counts']=={'canonicalHadithStructures':140,'publishedFrenchCanonicalEntries':90,'pendingPublishedFrenchCanonicalEntries':50});check('french-canonical-rc002',len(frce)==90 and [e['canonicalId'] for e in frce][-5:]==['RC-005','RC-006','RC-046','RC-057','RC-065'] and len({e['canonicalId'] for e in frce})==90);check('french-canonical-version',frc['sourcePolicy']['frenchTranslationVersion']=='v1.17.0' and frce[0]['sourceTranslationVersion']=='v1.17.0');check('french-canonical-ready',frce[0]['productionReady'] is True and frce[0]['explicitRevisionWarningObserved'] is False and bool(frce[0]['publishedFrenchTranslation']));check('french-canonical-safe',frc['assertions']=={'translationSynthesized':False,'translationModified':False,'sourceVersionInvented':False,'sourceWarningIgnored':False,'canonicalReligiousIdentityChanged':False,'runtimeChanged':False,'runtimeIntegrationAuthorized':False})
frs=load('data/religious-library-hadith-french-source-resolution-audit-v1.json'); frse=frs['entries']
check('french-resolution-release',frs['release']=='V141');check('french-resolution-ids',[x['canonicalId'] for x in frse]==['RC-001','RC-004']);check('french-resolution-source-ids',[x['sourceHadithId'] for x in frse]==[10101,6615]);check('french-resolution-404',all(x['officialFrenchRouteResult']=='404_PAGE_NOT_FOUND' for x in frse));check('french-resolution-none-promoted',frs['counts']['translationsPromoted']==0 and all(x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in frse));check('french-resolution-safe',frs['assertions']=={'translationSynthesized':False,'missingFrenchPageTreatedAsTranslation':False,'canonicalReligiousIdentityChanged':False,'runtimeChanged':False,'runtimeIntegrationAuthorized':False})
check('release',sup['release']=='V135');check('canonical-count',len(cs)==71);check('canonical-ids-unique',len(ids)==len(set(ids)));check('promoted-ids',ids[-2:]==['N-087','N-088']);check('legacy-supplement-refs-disjoint',legacy_refs.isdisjoint(supplement_refs))
refs={x['id']:x['primaryRef'] for x in cs}; check('N-048-ref',refs['N-048']=='Sahih al-Bukhari 6000');check('N-049-ref',refs['N-049']=='Sahih Muslim 2751a');check('N-050-ref',refs['N-050']=='Sahih al-Bukhari 7405')
for x in cs[-3:]: check(x['id']+'-safety',x['historicalHId'] is None and x['publishedFrenchTranslation'] is None and x['referenceVerified'] is True and x['historicalIdentityRecovered'] is False)
b=load('data/religious-library-hadith-new-authenticated-candidates-batch11-v1.json');check('batch11-promoted',all(x['auditDecision']=='PROMOTED_V109' for x in b['candidates']));check('no-r077-remap',b['assertions']['r077Remapped'] is False)
b12=load('data/religious-library-hadith-new-authenticated-candidates-batch12-v1.json'); b12ids=[x['id'] for x in b12['candidates']]
check('batch12-release',b12['targetRelease']=='V111');check('batch12-ids',b12ids==['N-051','N-052','N-053']);check('batch12-verified',all(x['referenceVerified'] is True for x in b12['candidates']));check('batch12-promoted',b12['assertions']['candidatesNotYetCanonical'] is False and b12['counts']['canonicalCountImpactUntilPromotion']==3 and all(x['auditDecision']=='PROMOTED_V111' for x in b12['candidates']));check('N-053-related-not-parallel',b12['candidates'][2]['relationReview']['classification']=='RELATED_NOT_AUTOMATIC_PARALLEL')
b13=load('data/religious-library-hadith-new-authenticated-candidates-batch13-v1.json'); b13ids=[x['id'] for x in b13['candidates']]
check('batch13-release',b13['targetRelease']=='V113');check('batch13-ids',b13ids==['N-054','N-055','N-056']);check('batch13-verified',all(x['referenceVerified'] is True for x in b13['candidates']));check('batch13-promoted',b13['assertions']['candidatesNotYetCanonical'] is False and b13['counts']['canonicalCountImpactUntilPromotion']==3 and all(x['auditDecision']=='PROMOTED_V113' for x in b13['candidates']));check('batch13-safety',all(x['historicalHId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b13['candidates']))
b14=load('data/religious-library-hadith-new-authenticated-candidates-batch14-v1.json'); b14ids=[x['id'] for x in b14['candidates']]
check('batch14-release',b14['targetRelease']=='V115');check('batch14-ids',b14ids==['N-057','N-058','N-059']);check('batch14-verified',all(x['referenceVerified'] is True and x['exactReferenceDuplicateInCurrentCanon'] is False for x in b14['candidates']));check('batch14-promoted',b14['assertions']['candidatesNotYetCanonical'] is False and b14['counts']['canonicalCountImpactUntilPromotion']==3 and all(x['auditDecision']=='PROMOTED_V115' for x in b14['candidates']));check('batch14-safety',all(x['historicalHId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b14['candidates']))
check('batch14-canonical-once',all(ids.count(x['id'])==1 for x in b14['candidates']))
b15=load('data/religious-library-hadith-new-authenticated-candidates-batch15-v1.json'); b15ids=[x['id'] for x in b15['candidates']]
check('batch15-release',b15['targetRelease']=='V117');check('batch15-ids',b15ids==['N-060','N-061','N-062']);check('batch15-verified',all(x['referenceVerified'] is True and x['exactReferenceDuplicateInCurrentCanon'] is False for x in b15['candidates']));check('batch15-promoted',b15['assertions']['candidatesNotYetCanonical'] is False and b15['counts']['canonicalCountImpactUntilPromotion']==3 and all(x['auditDecision']=='PROMOTED_V117' for x in b15['candidates']));check('batch15-safety',all(x['historicalHId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b15['candidates']));check('batch15-canonical-once',all(ids.count(x['id'])==1 for x in b15['candidates']))
b16=load('data/religious-library-hadith-new-authenticated-candidates-batch16-v1.json'); b16ids=[x['id'] for x in b16['candidates']]
check('batch16-release',b16['targetRelease']=='V119');check('batch16-ids',b16ids==['N-063','N-064','N-065']);check('batch16-verified',all(x['referenceVerified'] is True and x['exactReferenceDuplicateInCurrentCanon'] is False for x in b16['candidates']));check('batch16-promoted',b16['assertions']['candidatesNotYetCanonical'] is False and b16['counts']['canonicalCountImpactUntilPromotion']==3 and all(x['auditDecision']=='PROMOTED_V119' for x in b16['candidates']));check('batch16-safety',all(x['historicalHId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b16['candidates']));check('batch16-canonical-once',all(ids.count(x['id'])==1 for x in b16['candidates']));check('N-065-related-not-duplicate',b16['candidates'][2]['relationReview']['classification']=='RELATED_NOT_DUPLICATE')
b17=load('data/religious-library-hadith-new-authenticated-candidates-batch17-v1.json'); b17ids=[x['id'] for x in b17['candidates']]
check('batch17-release',b17['targetRelease']=='V121');check('batch17-ids',b17ids==['N-066','N-067','N-068']);check('batch17-verified',all(x['referenceVerified'] is True and x['exactReferenceDuplicateInCurrentCanon'] is False for x in b17['candidates']));check('batch17-promoted',b17['assertions']['candidatesNotYetCanonical'] is False and b17['counts']['canonicalCountImpactUntilPromotion']==3 and all(x['auditDecision']=='PROMOTED_V121' for x in b17['candidates']));check('batch17-safety',all(x['historicalHId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b17['candidates']));check('batch17-canonical-once',all(ids.count(x['id'])==1 for x in b17['candidates']));check('N-067-related-not-duplicate',b17['candidates'][1]['relationReview']['classification']=='RELATED_NOT_DUPLICATE');check('N-068-related-not-duplicate',b17['candidates'][2]['relationReview']['classification']=='RELATED_NOT_DUPLICATE')
b18=load('data/religious-library-hadith-new-authenticated-candidates-batch18-v1.json'); b18ids=[x['id'] for x in b18['candidates']]
check('batch18-release',b18['targetRelease']=='V123');check('batch18-ids',b18ids==['N-069','N-070','N-071']);check('batch18-verified',all(x['referenceVerified'] is True and x['exactReferenceDuplicateInCurrentCanon'] is False for x in b18['candidates']));check('batch18-promoted',b18['assertions']['candidatesNotYetCanonical'] is False and b18['counts']['canonicalCountImpactUntilPromotion']==3 and all(x['auditDecision']=='PROMOTED_V123' for x in b18['candidates']));check('batch18-safety',all(x['historicalHId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b18['candidates']));check('batch18-canonical-once',all(ids.count(x['id'])==1 for x in b18['candidates']));check('N-069-related-not-duplicate',b18['candidates'][0]['relationReview']['classification']=='RELATED_NOT_DUPLICATE')
b19=load('data/religious-library-hadith-new-authenticated-candidates-batch19-v1.json'); b19ids=[x['id'] for x in b19['candidates']]
check('batch19-release',b19['targetRelease']=='V126');check('batch19-ids',b19ids==['N-072','N-073','N-074']);check('batch19-rejected',b19['assertions']['candidatesNotYetCanonical'] is True and b19['counts']['canonicalCountImpactUntilPromotion']==0 and all(x['auditDecision']=='REJECTED_EXACT_REFERENCE_DUPLICATE_V126' and x['exactReferenceDuplicateInCurrentCanon'] is True for x in b19['candidates']));check('batch19-safety',all(x['historicalHId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b19['candidates']));check('batch19-legacy-duplicates',all(x['primaryRef'] in legacy_refs and x['duplicateReview']['classification']=='EXACT_REFERENCE_DUPLICATE' for x in b19['candidates']))
b20=load('data/religious-library-hadith-new-authenticated-candidates-batch20-v1.json'); b20ids=[x['id'] for x in b20['candidates']]
check('batch20-release',b20['targetRelease']=='V127');check('batch20-ids',b20ids==['N-075','N-076','N-077']);check('batch20-verified',all(x['referenceVerified'] is True and x['exactReferenceDuplicateInCurrentCanon'] is False for x in b20['candidates']));check('batch20-promoted',b20['assertions']['candidatesNotYetCanonical'] is False and b20['counts']['canonicalCountImpactUntilPromotion']==3 and all(x['auditDecision']=='PROMOTED_V127' for x in b20['candidates']));check('batch20-safety',all(x['historicalHId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b20['candidates']));check('batch20-canonical-once',all(ids.count(x['id'])==1 for x in b20['candidates']));check('N-075-related-not-duplicate',b20['candidates'][0]['relationReview']['classification']=='RELATED_NOT_DUPLICATE');check('N-076-related-not-duplicate',b20['candidates'][1]['relationReview']['classification']=='RELATED_NOT_DUPLICATE')
b21=load('data/religious-library-hadith-new-authenticated-candidates-batch21-v1.json'); b21ids=[x['id'] for x in b21['candidates']]
check('batch21-release',b21['targetRelease']=='V129');check('batch21-ids',b21ids==['N-078','N-079','N-080']);check('batch21-verified',all(x['referenceVerified'] is True and x['exactReferenceDuplicateInCurrentCanon'] is False for x in b21['candidates']));check('batch21-promoted',b21['assertions']['candidatesNotYetCanonical'] is False and b21['counts']['canonicalCountImpactUntilPromotion']==3 and all(x['auditDecision']=='PROMOTED_V129' for x in b21['candidates']));check('batch21-safety',all(x['historicalHId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b21['candidates']));check('batch21-canonical-once',all(ids.count(x['id'])==1 for x in b21['candidates']));check('N-078-related-not-duplicate',b21['candidates'][0]['relationReview']['classification']=='RELATED_NOT_DUPLICATE');check('N-079-related-not-duplicate',b21['candidates'][1]['relationReview']['classification']=='RELATED_NOT_DUPLICATE')
b22=load('data/religious-library-hadith-new-authenticated-candidates-batch22-v1.json'); b22ids=[x['id'] for x in b22['candidates']]
check('batch22-release',b22['targetRelease']=='V131');check('batch22-ids',b22ids==['N-081','N-082','N-083']);check('batch22-verified',all(x['referenceVerified'] is True and x['exactReferenceDuplicateInCurrentCanon'] is False for x in b22['candidates']));check('batch22-promoted',b22['assertions']['candidatesNotYetCanonical'] is False and b22['counts']['canonicalCountImpactUntilPromotion']==3 and all(x['auditDecision']=='PROMOTED_V131' for x in b22['candidates']));check('batch22-safety',all(x['historicalHId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b22['candidates']));check('batch22-canonical-once',all(ids.count(x['id'])==1 for x in b22['candidates']));check('N-082-related-not-duplicate',b22['candidates'][1]['relationReview']['classification']=='RELATED_NOT_DUPLICATE');check('N-083-related-not-duplicate',b22['candidates'][2]['relationReview']['classification']=='RELATED_NOT_DUPLICATE')
b23=load('data/religious-library-hadith-new-authenticated-candidates-batch23-v1.json'); b23ids=[x['id'] for x in b23['candidates']]
check('batch23-release',b23['sourceRelease']=='V132' and b23['targetRelease']=='V133');check('batch23-ids',b23ids==['N-084','N-085','N-086']);check('batch23-verified',all(x['referenceVerified'] is True and x['exactReferenceDuplicateInCurrentCanon'] is False for x in b23['candidates']));check('batch23-promoted',b23['assertions']['candidatesNotYetCanonical'] is False and b23['assertions']['religiousCorpusChanged'] is True and b23['counts']['canonicalCountImpactUntilPromotion']==3 and all(x['auditDecision']=='PROMOTED_V133' and x['status']=='NEW_AUTHENTICATED_CANONICAL_STRUCTURE' for x in b23['candidates']));check('batch23-safety',all(x['historicalHId'] is None and x['reconstructionRId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b23['candidates']));check('batch23-canonical-once',all(ids.count(x['id'])==1 for x in b23['candidates']))
check('N-084-related-not-duplicate',b23['candidates'][0]['relationReview']['classification']=='RELATED_NOT_DUPLICATE');check('N-085-related-not-duplicate',b23['candidates'][1]['relationReview']['classification']=='RELATED_NOT_DUPLICATE')
b24=load('data/religious-library-hadith-new-authenticated-candidates-batch24-v1.json'); b24ids=[x['id'] for x in b24['candidates']]
check('batch24-release',b24['sourceRelease']=='V134' and b24['targetRelease']=='V135');check('batch24-ids',b24ids==['N-087','N-088']);check('batch24-verified',all(x['referenceVerified'] is True and x['exactReferenceDuplicateInCurrentCanon'] is False for x in b24['candidates']));check('batch24-promoted',b24['assertions']['candidatesNotYetCanonical'] is False and b24['assertions']['religiousCorpusChanged'] is True and b24['counts']['canonicalCountImpactUntilPromotion']==2 and all(x['auditDecision']=='PROMOTED_V135' and x['status']=='NEW_AUTHENTICATED_CANONICAL_STRUCTURE' for x in b24['candidates']));check('batch24-safety',all(x['historicalHId'] is None and x['reconstructionRId'] is None and x['publishedFrenchTranslation'] is None and x['productionReady'] is False for x in b24['candidates']));check('batch24-canonical-once',all(ids.count(x['id'])==1 for x in b24['candidates']));check('N-087-related-not-duplicate',b24['candidates'][0]['relationReview']['classification']=='RELATED_NOT_DUPLICATE')
h=load('data/religious-library-hadith-coverage-ledger-v1.json')['slots'];check('hadith-slots',len(h)==140);check('hadith-canonical',sum(x.get('canonicalId') is not None for x in h)==140);check('hadith-gaps',sum(x.get('canonicalId') is None for x in h)==0)
for i,n in zip(range(102,105),range(48,51)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(105,108),range(51,54)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(108,111),range(54,57)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(111,114),range(57,60)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(114,117),range(60,63)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(117,120),range(63,66)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(120,123),range(66,69)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(123,126),range(69,72)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(126,129),range(75,78)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(129,132),range(78,81)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(132,135),range(81,84)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(135,138),range(84,87)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
for i,n in zip(range(138,140),range(87,89)): check(f'slot-{i+1}',h[i]['canonicalId']==f'N-{n:03d}' and h[i]['gapId']==f'GAP-{i-68:03d}')
g=load('data/religious-library-corpus-coverage-ledger-v1.json');check('global-slots',len(g['slots'])==183);check('global-counts',g['counts']['hadithCanonicalStructures']==140 and g['counts']['hadithAdministrativeGaps']==0 and g['counts']['unmaterializedPositions']==0 and g['counts']['materializedReligiousStructures']==183)
m=load('data/religious-library-target-manifest.json');check('target-manifest-release',m['release']=='V145' and 'CURRENT_FOR_V136' not in json.dumps(m))
r77=load('data/religious-library-hadith-r077-evidence-audit-v1.json');check('R-077-quarantined','R-077' in json.dumps(r77) and 'QUARANTIN' in json.dumps(r77).upper() and b['assertions']['r077Remapped'] is False)
check('runtime-shell-current', (R/'index.html').is_file() and (R/'app.js').is_file() and (R/'sw.js').is_file() and re.search(r'const BUILD_VERSION = (\d+);', (R/'app.js').read_text('utf-8')) is not None and re.search(r'build (\d+)', (R/'index.html').read_text('utf-8')) is not None and re.search(r"const CACHE = 'jardin-du-coeur-v(\d+)'", (R/'sw.js').read_text('utf-8')) is not None and re.search(r'const BUILD_VERSION = (\d+);', (R/'app.js').read_text('utf-8')).group(1) == re.search(r'build (\d+)', (R/'index.html').read_text('utf-8')).group(1) == re.search(r"const CACHE = 'jardin-du-coeur-v(\d+)'", (R/'sw.js').read_text('utf-8')).group(1))
bad=[]
for p in sorted((R/'data').glob('*.json')):
 try: json.loads(p.read_text('utf-8'))
 except Exception as e: bad.append(f'{p.name}:{e}')
check('all-json-parse',not bad,';'.join(bad));check('production-not-ready',all(x['frenchTextStatus']=='PENDING_PUBLISHED_FRENCH_PROVENANCE' for x in cs[-3:]))

fr12=load('data/religious-library-hadith-french-bulk-twelfth-pass-audit-v185.json')
check('french-bulk12-release',fr12['release']=='V185')
check('french-bulk12-scope',fr12['scope']=={'reviewedCanonicalIds':['RC-057','RC-065'],'reviewedCount':2})
check('french-bulk12-held',fr12['promotedCanonicalIds']==[] and fr12['heldCanonicalIds']==['RC-057','RC-065'] and fr12['heldCount']==2)
check('french-bulk12-counts',fr12['countsAfter']=={'canonicalHadithStructures':140,'publishedFrenchCanonicalEntries':80,'pendingPublishedFrenchCanonicalEntries':60})
check('french-bulk12-safe',fr12['assertions']=={'translationSynthesized':False,'revisionWarningIgnored':False,'nonPolicySourcePromoted':False,'runtimeChanged':False,'runtimeIntegrationAuthorized':False})

frp2=load('data/religious-library-hadith-french-multisource-protocol-v2.json')
check('french-multisource-v2-release',frp2['release']=='V186')
check('french-multisource-v2-sources',[x['sourceId'] for x in frp2['sources']]==['HADEETHENC','ISLAMHOUSE','SUNNATY'])
check('french-multisource-v2-counts',frp2['countsAfter']=={'publishedFrenchCanonicalEntries':80,'pendingPublishedFrenchCanonicalEntries':60})
check('french-multisource-v2-safe',frp2['assertions']=={'translationSynthesized':False,'existingFrenchTranslationsModified':False,'canonicalReligiousIdentityChanged':False,'runtimeChanged':False,'runtimeIntegrationAuthorized':False})
check('french-multisource-v2-policy',frc['sourcePolicy']['policyMode']=='MULTISOURCE_VERIFIED_FRENCH_V2' and [x['sourceId'] for x in frc['sourcePolicy']['authorizedSourceChannels']]==['HADEETHENC','ISLAMHOUSE','SUNNATY'])
fr197=load('data/religious-library-hadith-french-multisource-continuation-v197.json')
check('french-v197-release',fr197['release']=='V197')
check('french-v197-promoted',fr197['promotedCanonicalIds']==['RC-061'] and fr197['heldCanonicalIds']==['RC-057','RC-065','RC-004'])
check('french-v197-counts',fr197['countsAfter']=={'canonicalHadithStructures':140,'publishedFrenchCanonicalEntries':85,'pendingPublishedFrenchCanonicalEntries':55})
check('french-v197-source',any(e['canonicalId']=='RC-061' and e['sourcePublisher']=='IslamHouse.com' and e['sourceTranslator']=='Mohammed Yacine KASSAB' and e['productionReady'] is True for e in frce))
fr198=load('data/religious-library-hadith-french-multisource-continuation-v198.json')
check('french-v198-release',fr198['release']=='V198')
check('french-v198-promoted',fr198['promotedCanonicalIds']==['RC-005','RC-006','RC-046','RC-057','RC-065'])
check('french-v198-counts',fr198['countsAfter']=={'canonicalHadithStructures':140,'publishedFrenchCanonicalEntries':90,'pendingPublishedFrenchCanonicalEntries':50})
check('french-v198-source',all(e['sourcePublisher']=='IslamHouse.com' and e['sourceTranslator']=='Rachid Maach' and e['productionReady'] is True for e in frce[-5:]))
check('french-v197-safe',fr197['assertions']=={'translationSynthesized':False,'translationModified':False,'revisionWarningIgnored':False,'canonicalReligiousIdentityChanged':False,'runtimeChanged':False,'runtimeIntegrationAuthorized':False})

pg=load('data/religious-library-hadith-preservation-guard-v1.json')
pgids=pg['preservedWithoutFinalFrenchValidation']
canonical_hadith_ids=[x['payload']['canonicalId'] if x['corpusPart']=='hadithLegacy' else x['payload']['id'] for x in ue if x['corpusPart'] in ('hadithLegacy','hadithSupplement')]
check('preservation-v199-release',pg['release']=='V199')
check('preservation-v199-140',len(canonical_hadith_ids)==140 and len(set(canonical_hadith_ids))==140 and pg['counts']['preservedCanonicalIds']==140)
check('preservation-v199-50',len(pgids)==50 and set(pgids)==set(canonical_hadith_ids)-{x['canonicalId'] for x in frce})
check('preservation-v199-no-delete',pg['policy']['canonicalHadithDeletionAllowed'] is False and pg['policy']['untranslatedHadithDeletionAllowed'] is False and pg['policy']['buildMustFailIfCanonicalIdDisappears'] is True)
check('preservation-v199-safe',pg['assertions']=={'all140CanonicalIdsPreserved':True,'all50UnfinalizedIdsRemainCanonical':True,'canonicalReligiousIdentityChanged':False,'runtimeChanged':False,'runtimeIntegrationAuthorized':False})

v200=load('data/religious-library-hadith-french-consolidation-evidence-v200.json')
n030=next(x for x in cs if x['id']=='N-030')
check('v200-release',v200['release']=='V200')
check('v200-preservation',v200['counts']['canonicalHadithStructures']==140 and v200['counts']['publishedFrenchCanonicalEntries']==90 and v200['counts']['preservedFrenchToConsolidate']==50)
check('v200-n030-correction',n030['primaryRef']=='Sahih Muslim 2707' and n030['inBookReference']=='Book 48, Hadith 71' and n030['sourceUrl']=='https://sunnah.com/muslim:2707')
check('v200-no-unauthorized-promotion',v200['counts']['newFinalPromotions']==0 and v200['assertions']['unauthorizedFrenchSourcePromoted'] is False and all(x['canonicalId'] not in {e['canonicalId'] for e in frce} for x in v200['entries'] if x['canonicalId'] in ('RC-019','RC-020')))
check('v200-safe',v200['assertions']['all140CanonicalIdsPreserved'] is True and v200['assertions']['unfinalizedHadithDeleted'] is False and v200['assertions']['translationSynthesized'] is False and v200['assertions']['runtimeChanged'] is False)


v201=load('data/religious-library-hadith-french-consolidation-evidence-v201.json')
check('v201-release',v201['release']=='V201')
check('v201-scope',v201['scope']=={'reviewedCanonicalIds':['RC-026','RC-028','RC-029'],'reviewedCount':3})
check('v201-preservation',v201['counts']['canonicalHadithStructures']==140 and v201['counts']['publishedFrenchCanonicalEntries']==90 and v201['counts']['preservedFrenchToConsolidate']==50)
check('v201-evidence',v201['counts']['newFullFrenchMatchesRecorded']==3 and v201['counts']['newFinalPromotions']==0)
check('v201-safe',v201['assertions']=={'all140CanonicalIdsPreserved':True,'unfinalizedHadithDeleted':False,'translationSynthesized':False,'partialTranslationPromoted':False,'unauthorizedFrenchSourcePromoted':False,'runtimeChanged':False,'runtimeIntegrationAuthorized':False})


fr202=load('data/religious-library-hadith-french-consolidation-evidence-v202.json')
check('french-v202-release',fr202['release']=='V202')
check('french-v202-scope',fr202['scope']=={'reviewedCanonicalIds':['RC-022'],'reviewedCount':1})
check('french-v202-counts',fr202['counts']=={'canonicalHadithStructures':140,'publishedFrenchCanonicalEntries':90,'preservedFrenchToConsolidate':50,'newFinalPromotions':0,'newFullFrenchMatchesRecorded':1})
check('french-v202-held',fr202['entries'][0]['canonicalId']=='RC-022' and fr202['entries'][0]['decision']=='PRESERVE_AND_HOLD' and fr202['entries'][0]['fullMatnMatch'] is True)
check('french-v202-safe',fr202['assertions']['canonicalHadithLoss'] is False and fr202['assertions']['translationSynthesized'] is False and fr202['assertions']['runtimeChanged'] is False)

print(f'Checks: {okc+fail} | PASS: {okc} | FAIL: {fail}');sys.exit(1 if fail else 0)
