#!/usr/bin/env python3
from pathlib import Path
import json,sys
R=Path(__file__).resolve().parents[1]
index=(R/'index.html').read_text('utf-8'); js=(R/'app.js').read_text('utf-8'); css=(R/'app.css').read_text('utf-8'); sw=(R/'sw.js').read_text('utf-8'); manifest=json.loads((R/'manifest.webmanifest').read_text('utf-8'))
checks={
'app-version': "const APP_VERSION = '2.1.22'" in js and 'const BUILD_VERSION = 288' in js,
'external-assets': './app.css' in index and './app.js' in index and '<style' not in index.lower(),
'schema-version':'const DATA_SCHEMA_VERSION = 1' in js,
'storage-key-preserved':"const STORAGE_KEY = 'jardin-du-coeur-v1'" in js,
'import-compatible':'parsed.data||parsed' in js,
'import-normalized':'normalizeImportedState' in js,
'import-size-limit':'5*1024*1024' in js,
'dark-theme-complete':'.theme-dark .screen' in css and '.theme-dark .modal' in css,
'sw-v278':"const CACHE = 'jardin-du-coeur-v288'" in sw,
'sw-core-assets':"'./app.css'" in sw and "'./app.js'" in sw,
'sw-navigation-fallback-only':"request.mode === 'navigate'" in sw,
'sw-same-origin-cache':"url.origin !== self.location.origin" in sw,
'manifest-standalone':manifest.get('display')=='standalone',
'icons-present':all((R/p).is_file() for p in ['icons/icon-192.png','icons/icon-512.png','icons/icon-maskable-512.png']),
'workflow-minimal-artifact':'path: _site' in (R/'.github/workflows/deploy-pages.yml').read_text('utf-8'),
'corpus-standby-marker':(R/'CORPUS-STANDBY.sha256').is_file(),
'pwa-update-prompt':"showUpdateReady" in js and "SKIP_WAITING" in js,
'pwa-controller-reload':"controllerchange" in js and "refreshingFromServiceWorker" in js,
'pwa-connectivity-feedback':"addEventListener('offline'" in js and "addEventListener('online'" in js,
'sw-controlled-activation':"self.addEventListener('message'" in sw and "self.skipWaiting()" in sw,
'sw-owned-cache-cleanup':"key.startsWith(CACHE_PREFIX)" in sw,
'manifest-stable-id':manifest.get('id')=='./' and manifest.get('start_url')=='./',
'access-modal-focus':'modalReturnFocus' in js and 'modalFocusable' in js,
'access-modal-escape':"e.key==='Escape'" in js,
'access-modal-tab-trap':"e.key==='Tab'" in js,
'access-form-names':"noms accessibles de repli" in js,
'access-forced-colors':'forced-colors:active' in css,
'access-more-contrast':'prefers-contrast:more' in css,
'perf-no-inline-daily-images':'data:image/jpeg;base64' not in js,
'perf-daily-assets':all((R/f'assets/daily/daily-{i:02d}.jpg').is_file() for i in range(1,13)),
'perf-daily-precache':all(f"'./assets/daily/daily-{i:02d}.jpg'" in sw for i in range(1,13)),
'v265-book-children-direct-access': 'data-book-lesson="book-wadiiyya-children">Enfants & transmission</button>' in js,
'perf-js-under-176k':len(js.encode('utf-8')) < 180000,  # budget raised: +~1.4k for the PIN-lock security feature (audit fix)
'ui-version-current':'Version 2.1.22 PWA · build 288' in index,
'v274-faith-categories':'data-faith-category="books"' in index and "a.cat='books'" in js,
'v274-faith-source-labels':all(x in js for x in ['Sources primaires vérifiées','Avis juridiques documentés','Leçon d’ouvrage documentée']),
'v274-faith-new-lessons':all(x in js for x in ["id:'spiritual-prayer'","id:'spiritual-dhikr'","id:'spiritual-steadiness'","id:'life-mother'","id:'life-menopause'"]),
'v274-faith-consolidation':'FAITH_ARCHIVED_IDS' in js and 'visibleFaithArticles()' in js,
'v275-faith-editorial-review':all(x in js for x in ["id:'spiritual-tawakkul'","id:'life-before-marriage'","status:'pending'","Sahih Muslim 2735a","Sahih al-Bukhari 6465"]),
'v276-dua-acceptance':all(x in js for x in ["id:'spiritual-dua-acceptance'",'Les causes qui favorisent l’exaucement de l’invocation','Jami‘ at-Tirmidhi 3477','Sahih al-Bukhari 6338','Sahih Muslim 2735c','Sahih Muslim 482','Sahih al-Bukhari 1145','Sunan Abi Dawud 521','Sahih Muslim 1015']),
'v277-dua-prophet-example':all(x in js for x in ['Un exemple authentique','اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ','Allâhumma salli ‘alâ Muhammad','Sahih al-Bukhari 6357','Sahih Muslim 406a']),
'v278-tawakkul-expanded':all(x in js for x in ['Comprendre et vivre le tawakkul','Ce que le tawakkul n’est pas','Une mise en pratique','Coran 8:2','Jami‘ at-Tirmidhi 2344 — hasan']),
'v273-cycle-listen-hub':'data-cycle-action="listen"' in index and "action==='listen'" in js and (R/'cycle-listen.js').is_file(),
'v273-cycle-listen-content':all(x in (R/'cycle-listen.js').read_text('utf-8') for x in ['Récitations du Coran','Cours & rappels','https://quran.com/fr','listenFaithReminder']),
'v273-cycle-listen-precache':"'./cycle-listen.js'" in sw,
'v271-dua-authentic-addition':"id:'q1-6'" in (R/'dua-library.js').read_text('utf-8') and 'Coran 1:6 · QuranEnc / Muhammad Hamidullah' in (R/'dua-library.js').read_text('utf-8'),
'v271-dua-reference-dedup':'refs.has(r)' in (R/'dua-library.js').read_text('utf-8'),
'v270-dua-source-filters':'id="duaSources"' in index and all(x in index for x in ['Du‘â du Coran','Du‘â de la Sunna']),
'v270-dua-source-wired':'duaSource' in js and "d.grade.includes('Coran')?'Coran':'Sunna'" in js,
'v269-dua-library':(R/'dua-library.js').is_file() and 'JDC_DUA_LIBRARY_ADDITIONS' in (R/'dua-library.js').read_text('utf-8'),
'v269-dua-expanded':(R/'dua-library.js').read_text('utf-8').count("grade:'📖 Coran'") == 8,
'v269-dua-deduplicated':'texts.has(key)' in (R/'dua-library.js').read_text('utf-8') and 'ids.has(d.id)' in (R/'dua-library.js').read_text('utf-8'),
'v269-dua-precache':"'./dua-library.js'" in sw,
'robust-safe-storage':all(x in js for x in ['safeStorageGet','safeStorageSet','safeStorageRemove']),
'robust-runtime-error':"addEventListener('error'" in js,
'robust-unhandled-rejection':"addEventListener('unhandledrejection'" in js,
'robust-import-recovery':"throw new Error('recovery')" in js,


'ux-main-nav':'aria-label=\"Navigation principale\"' in js and 'aria-current' in js,
'ux-live-toast':'aria-live=\"polite\"' in index,
'ux-focus-visible':':focus-visible' in css,
'ux-reduced-motion':'prefers-reduced-motion' in css,
'ux-touch-targets':'min-width:44px' in css and 'min-height:44px' in css,
'data-recovery-key':"const RECOVERY_KEY = STORAGE_KEY + '-recovery'" in js,
'data-recovery-write':'safeStorageSet(RECOVERY_KEY, serialized)' in js,
'data-recovery-before-import':'saveRecoverySnapshot();' in js,
'data-recovery-on-corruption':'safeStorageGet(RECOVERY_KEY)' in js,
'data-clear-recovery':'safeStorageRemove(RECOVERY_KEY)' in js,
'v219-objective-history':'completedAt' in js and 'objectivesPanel' in js,
'v219-journal-recent':'journalRecent' in index and 'renderJournalRecent' in js,
'v220-progress-panel':'data-profile-panel="progress"' in index and 'progressPanel' in js,
'v220-progress-windows':'progressSnapshot(7)' in js and 'progressSnapshot(30)' in js,
'v220-progress-local-only':'données locales' in js or 'données enregistrées sur cet appareil' in js,
'v221-week-trends':'progressSnapshotRange(7,7)' in js and 'trendLabel' in js,
'v221-progress-actions':'data-progress-go' in js and 'progress-actions' in css,
'v222-history-actions':'homeHistoryBtn' in index and 'journalHistoryBtn' in index and 'openRecentHistory' in js,
'v222-no-dead-journal-tabs':'<button disabled aria-disabled="true" title="Vue à venir">Semaine</button>' in index,
'v222-no-dead-day-plus':'<h2>Ma journée</h2><span></span>' in index,
'v223-muhasabah-date':'muhasabahDate' in index and 'muhasabahDate' in js,
'v223-home-today-safety':"homeMuhasabahBtn')?.addEventListener('click',()=>{selectedDate=todayKey()" in js,
'v223-muhasabah-navigation':'muhasabahBackBtn' in index and 'muhasabahJournalBtn' in index and 'finishDayBtn' in index,
'v223-muhasabah-summary':'summaryMuhasabah' in index and 'reflectionCount' in js,
'v224-day-context':'dayDetailsDate' in index and 'dayDetailsDate' in js,
'v224-today-shortcut':'journalTodayBtn' in index and 'selectToday' in js,
'v224-future-guard':"target>todayKey()" in js and 'nextDay.disabled=atToday' in js,
'v224-journal-shortcut':'dayDetailsJournalBtn' in index and 'dayDetailsJournalBtn' in js,
'v224-no-decorative-plus':'data-field="heartNotes"' in index and 'Mon dhikr <span style="margin-left:auto"' not in index,
'v225-journal-review-first':"selectDate(b.dataset.journalDate,5)" in js and "selectDate(b.dataset.historyDate,5)" in js,
'v225-open-selected-day':'journalOpenDayBtn' in index and "journalOpenDayBtn')?.addEventListener" in js,
'v225-future-calendar-disabled':"b.disabled=true;b.classList.add('future')" in js,
'v225-future-month-disabled':"nextMonth.disabled=futureMonth" in js,
'v225-calendar-accessible':"b.setAttribute('aria-label',frDate(date,true)" in js,
'v226-day-progress':'daySectionProgress' in index and 'renderDaySectionProgress' in js,
'v226-day-today-shortcut':'dayDetailsTodayBtn' in index and 'selectToday(3)' in js,
'v226-day-flow-actions':'dayBackToBasicsBtn' in index and 'dayToMuhasabahBtn' in index,
'v227-objective-feedback':"toast('Objectif ajouté')" in js and "Objectif réactivé" in js,
'v227-habit-feedback':"toast('Habitude ajoutée')" in js and "Habitude cochée pour aujourd’hui" in js,
'v227-enter-add':"newObjectiveItem').addEventListener('keydown'" in js and "newHabitItem').addEventListener('keydown'" in js,
'v227-actionable-empty-states':'Commence par une habitude simple et réaliste.' in js and 'Ajoute ci-dessous un objectif qui compte pour toi.' in js,
'v228-flow-recipe':(R/'tests/test_user_flows.py').is_file(),
'v228-release-history-complete':(R/'RELEASE-V227.md').is_file() and (R/'RELEASE-V228.md').is_file(),
'v229-resume-session':"const UI_SESSION_KEY = STORAGE_KEY + '-ui-session'" in js and 'loadUiSession' in js and 'saveUiSession' in js,
'v229-save-feedback':"statusEl.textContent='Enregistrement…'" in js and 'Enregistré à ${new Date().toLocaleTimeString' in js,
'v230-contextual-resume':'dailyJourneyStatus' in js and 'homeJourneyHint' in index and "Continuer ma muhâsabah" in js,
'v230-smart-journal-row':"if(action==='journal'){startOrContinueDay()}" in js,
'v231-progress-clarity':'homeTodayProgressBar' in index and 'faits · ${remaining} à poursuivre' in js,
'v231-next-action':'homeTodayNextAction' in index and "addEventListener('click',startOrContinueDay)" in js,
'v231-status-labels':"'Fait aujourd’hui':'À faire aujourd’hui'" in js and "journalStarted?'◐':'○'" in js,
'v232-close-summary':'dayCloseSummary' in index and 'renderEveningSummary' in js,
'v232-finished-marker':'finishedAt' in js and "Journée clôturée et disponible dans le Journal" in js,
'v232-closed-resume':"if(d.finishedAt) return {screen:5" in js,
'v233-journal-status-helper':'function journalDayMeta' in js and "label:closed?'Clôturée':'En cours'" in js,
'v233-recent-status':'journal-day-status' in js and "meta.label" in js,
'v233-calendar-memory':"b.classList.add(state.days[k]?.finishedAt?'closed':'started')" in js and 'day.has.closed' in css,
'v234-history-search':'journalHistorySearch' in js and 'journalSearchText' in js,
'v234-history-filters':'data-history-filter=\"closed\"' in js and 'data-history-filter=\"started\"' in js,
'v234-history-all-days':"sort((a,b)=>b[0].localeCompare(a[0]));" in js and "slice(0,10)" not in js,
'v235-review-summary':'journalReview' in index and 'renderJournalReview' in js,
'v235-review-status':"journal-review-stats" in js and "meta.reflectionCount" in js,
'v235-review-highlights':all(x in js for x in ['Intention','Gratitude','Mot du jour']),
'v236-journal-day-navigation':all(x in index for x in ['journalPrevDay','journalNextDay','journalSelectedTodayBtn']) and "journalPrevDay')?.addEventListener" in js and "journalNextDay')?.addEventListener" in js,
'v236-journal-today-state':"journalToday.disabled=atToday" in js and "selectToday()" in js,
'v236-small-screen-navigation':'.journal-selected-nav' in css and '@media(max-width:380px)' in css,
'v237-consult-edit-actions':'journalEditDayBtn' in index and 'Consulter cette journée' in js and 'Modifier cette journée' in js,
'v237-readonly-past':'applyJournalViewMode' in js and 'el.readOnly=readOnly' in js and 'el.disabled=readOnly' in js,
'v237-edit-reversible':'data-enable-journal-edit' in js and 'data-disable-journal-edit' in js and 'setJournalEditMode' in js,
'v238-active-field':'field-active' in js and '.card.field-active,.prompt.field-active' in css,
'v238-muhasabah-keyboard':"(e.ctrlKey||e.metaKey)&&e.key==='Enter'" in js and "finishDayBtn')?.focus()" in js,
'v238-mobile-form-comfort':'min-height:108px' in css and 'font-size:16px' in css and 'scroll-margin-block:22vh' in css,
'v239-last-field-resume':"let lastActiveField = '';" in js and 'restoreLastActiveField(restoredUiSession)' in js and 'lastActiveField,updatedAt' in js,
'v239-exit-persistence':"window.addEventListener('pagehide',persistBeforeLeave)" in js and "document.visibilityState==='hidden'" in js,
'v239-save-live-status':'aria-live="polite"' in index and 'Enregistré à ${new Date().toLocaleTimeString' in js,
'v240-contextual-back':'dayBasicsBackBtn' in index and "go(selectedDate===todayKey()?1:5)" in js,
'v240-contextual-copy':"Voir ce que mon cœur porte" in js and "Voir la muhâsabah" in js,
'v241-core-control-labels':'aria-label="Mon intention du jour"' in index and 'aria-label="Statut de la prière Fajr"' in index and 'aria-label="Ma gratitude du jour"' in index,
'v241-mobile-input-size':'@media(max-width:650px){input,select,textarea{font-size:16px}' in css,
'v241-safe-areas':'env(safe-area-inset-left)' in css and 'env(safe-area-inset-right)' in css,
'v242-recovery-action':'restoreRecoveryBtn' in js and 'function restoreRecoveryData()' in js,
'v242-recovery-preserved':"safeStorageSet(RECOVERY_KEY,serialized)" not in js and 'saveRecoverySnapshot();' in js,
'v242-recovery-session-reset':'safeStorageRemove(UI_SESSION_KEY)' in js and 'Copie de récupération invalide' in js,
'v243-final-release-note':(R/'RELEASE-V243.md').is_file(),
'v243-contracts-frozen':"const DATA_SCHEMA_VERSION = 1" in js and "const STORAGE_KEY = 'jardin-du-coeur-v1'" in js,
'v243-final-flow-suite':(R/'tests/test_user_flows.py').is_file() and (R/'tests/test_app_regression.py').is_file(),
'v244-home-hierarchy':'home-start-card' in index and index.index('home-start-card') < index.index('home-prayer-preview') < index.index('home-today-dashboard'),
'v244-home-section-cues':index.count('home-card-kicker') >= 4 and 'home-screen-title' in index,
'v244-mood-state':"setAttribute('aria-pressed',String(selected))" in js and 'role="group" aria-label="État du cœur aujourd’hui"' in index,
'v245-day-intro':'day-basics-intro' in index and 'MES REPÈRES DU JOUR' in index,
'v245-visible-labels':index.count('day-field-label') >= 4 and 'day-verse-range' in index,
'v245-day-mobile':'/* V245 — interface 2 : Ma journée */' in css and '.screen[data-screen="2"] .status-pill' in css,
'v246-heart-intro':'heart-page-intro' in index and 'Ce que mon cœur porte' in index,
'v246-heart-labels':index.count('heart-field-label') >= 4 and 'heart-note-primary' in index,
'v246-heart-mobile':'/* V246 — interface 3 : Ce que mon cœur porte */' in css and '.heart-note-primary textarea' in css,


'v247-muhasabah-guide':'muhasabah-guide' in index and '6 questions' in index,
'v247-muhasabah-labels':index.count('aria-labelledby="muhasabah') == 6,
'v247-muhasabah-mobile':'/* V247 — interface 4 : Muhâsabah */' in css and '.muhasabah-reflection textarea' in css,
'v248-journal-intro':'journal-intro' in index and 'Retrouve le fil de tes journées' in index,
'v248-journal-legend':'journal-calendar-legend' in index and 'Calendrier du journal' in index,
'v248-journal-css':'/* V248 — interface 5 : Journal */' in css and '.journal-day-card' in css,

'v249-dua-intro':'dua-page-intro' in index and 'Un espace pour tes du‘â' in index,
'v249-dua-a11y':'role="tablist"' in index and 'duaResultsCount' in index and 'aria-live="polite"' in index,
'v249-dua-css':'/* V249 — interface 6 : Mes du‘â */' in css and '.dua-results-head' in css,
'v250-cycle-intro':'cycle-page-intro' in index and 'Observer mon cycle avec simplicité' in index,
'v250-cycle-a11y':'aria-label="Vue du cycle"' in index and 'aria-label="Calendrier du cycle"' in index and "setAttribute('aria-selected',String(selected))" in js,
'v250-cycle-css':'/* V250 — interface 7 : Mon cycle */' in css and '.cycle-calendar-intro' in css,
'v251-faith-hierarchy':'faith-trust-note' in index and 'faithResultsCount' in index and 'faith-section-head' in index,
'v251-faith-a11y':'aria-pressed="false" data-faith-category' in index and "setAttribute('aria-pressed',String(selected))" in js,
'v251-faith-css':'/* V251 — interface 8 : Comprendre & vivre sa foi */' in css and '.faith-row-meta' in css,
'v252-reflection-hierarchy':'reflection-page-intro' in index and 'reflection-guide' in index and 'reflection-period-copy' in index,
'v252-reflection-a11y':'role="tablist" aria-label="Période de réflexion"' in index and 'aria-label="Ce qui a rempli mon cœur"' in index and "setAttribute('aria-selected',String(selected))" in js,
'v252-reflection-css':'/* V252 — interface 9 : Réflexion périodique */' in css and '.reflection-period-card textarea' in css,
'v253-profile-hierarchy':'profile-page-intro' in index and index.count('profile-section-label') == 3,
'v253-profile-name-action':'profileNameBtn' in index and 'function openProfileNameEditor()' in js and 'for=\"displayNameInput\"' in js,
'v253-profile-css':'/* V253 — interface 10 : Moi / profil & réglages */' in css and '.profile-settings-group .profile-action' in css,
'v254-visual-tokens':'/* V254 — cohérence visuelle transversale */' in css and '--ui-radius' in css,
'v254-actions-consistency':'.primary,.secondary,.mini-btn' in css and '.screen>.card,.screen>.prompt' in css,
'v254-mobile-rhythm':'@media(max-width:380px)' in css and '.screen>.card' in css,
'v255-shared-components':'/* V255 — composants partagés' in css and '.bottom-nav button:focus-visible' in css,
'v255-modal-controls':'.modal-actions button{min-height:44px}' in css and '.modal-close{min-width:44px;min-height:44px' in css,
'v255-form-focus':'input:focus-visible,textarea:focus-visible,select:focus-visible' in css,
'v256-faith-paths':'data-faith-path="cycle"' in index and 'data-faith-path="books"' in index,
'v256-cycle-learning':'id="cycleLearnBtn"' in index and "openFaithPath('cycle')" in js,
'v256-books-method':'function openFaithBooks()' in js and 'faith-book-method' in js,
'v256-faith-css':'/* V256 — parcours Islam au féminin' in css,
'v257-book-lesson':"id:'book-muhaddithat'" in js and 'data-book-lesson=\"book-muhaddithat\"' in js,
'v257-book-bibliography':'Al-Muḥaddithāt: The Women Scholars in Islam' in js and 'A Treatise on Women’s Natural Types of Bleeding' in js,
'v257-book-css':'/* V257 — premières leçons issues d’ouvrages vérifiés */' in css,

'v258-cycle-book-method': "id:'book-natural-bleeding'" in js and 'data-book-lesson=\"book-natural-bleeding\"' in js,
'v258-nifas-lesson': "id:'body-nifas'" in js and 'Sunan Ibn Majah 648' in js,
'v258-uncertain-lesson': "id:'body-uncertain'" in js and 'calendrier est un journal' in js,
'v258-cycle-css': '/* V258 — cycle : approfondissement pédagogique ḥayḍ, istiḥāḍa et nifâs */' in css,
'v259-purity-signs': "id:'body-purity-signs'" in js and 'Sahih al-Bukhari 331' in js,
'v259-yellow-brown': "id:'body-yellow-brown'" in js and 'Sunan Abi Dawud 307' in js,
'v259-fast-makeup': "id:'ramadan-makeup'" in js and 'Sahih Muslim 335c' in js,
'v259-cycle-css': '/* V259 — fin des règles, purification et reprise des adorations */' in css,
'v260-ghusl-practical': "id:'body-ghusl-practical'" in js and 'Sahih Muslim 332c' in js,
'v260-istihada-practical': "id:'body-istihada-practical'" in js and 'Sahih al-Bukhari 228' in js,
'v260-safety-boundary': 'ne possède pas de bouton « ghusl validé »' in js and 'Deux questions différentes' in js,
'v260-cycle-css': '/* V260 — ghusl pratique et saignements irréguliers */' in css,
'v261-book-entry': 'Conseils aux femmes musulmanes — suivi de questions-réponses' in js and 'Umm ‘Abdillah Al-Wâdi‘iyya' in js,
'v261-three-lessons': all(("id:'"+x+"'") in js for x in ['book-wadiiyya-time','book-wadiiyya-knowledge','book-wadiiyya-sisters']),
'v261-primary-sources': 'Sahih al-Bukhari 101' in js and 'Coran 9:71' in js and 'Coran 103:1–3' in js,
'v261-book-css': '/* V261 — Conseils aux femmes musulmanes : parcours de leçons */' in css,
'v263-three-lessons': all(("id:'"+x+"'") in js for x in ['book-wadiiyya-sincerity','book-wadiiyya-modesty','book-wadiiyya-family']),
'v263-primary-sources': all(x in js for x in ['Coran 98:5','Coran 24:30–31','Coran 30:21']),

# --- Audit securite/robustesse ---
'security-csp-meta': 'Content-Security-Policy' in index and "connect-src 'none'" in index,
'security-deploy-includes-all-scripts': 'cp index.html app.css app.js icons-ui.js dua-library.js cycle-listen.js sw.js manifest.webmanifest .nojekyll _site/' in (R/'.github/workflows/deploy-pages.yml').read_text('utf-8'),
'security-crypto-uid': 'crypto.randomUUID' in js,
'security-lock-feature': all(x in js for x in ['LOCK_KEY','setLockPin','verifyLockPin','initLockScreen']) and 'lockScreen' in index,
'security-lock-hashed-not-plaintext': 'sha256Hex(salt+pin)' in js,
}
failed=[k for k,v in checks.items() if not v]
for k,v in checks.items(): print(('PASS' if v else 'FAIL'),k)
print(f'{len(checks)-len(failed)}/{len(checks)} application checks passed')
sys.exit(bool(failed))
